export const CountryCodes = [
    {"code": "AD", "description": "Andorra"},
    {"code": "AE", "description": "United Arab Emirates"},
    {"code": "AF", "description": "Afghanistan 2"},
    {"code": "AG", "description": "Antigua And Barbuda"},
    {"code": "AI", "description": "Anguilla"},
    {"code": "AL", "description": "Albania"},
    {"code": "AM", "description": "Armenia"},
    {"code": "AN", "description": "Netherlands Antilles"},
    {"code": "AO", "description": "Angola"},
    {"code": "AQ", "description": "Antarctica"},
    {"code": "AR", "description": "Argentina"},
    {"code": "AS", "description": "American Samoa"},
    {"code": "AT", "description": "Austria"},
    {"code": "AU", "description": "Australia"},
    {"code": "AW", "description": "Aruba"},
    {"code": "AZ", "description": "Azerbaijan"},
    {"code": "BA", "description": "Bosnia And Herzegowina"},
    {"code": "BB", "description": "Barbados"},
    {"code": "BD", "description": "Bangladesh"},
    {"code": "BE", "description": "Belgium"},
    {"code": "BF", "description": "Burkina Faso"},
    {"code": "BG", "description": "Bulgaria"},
    {"code": "BH", "description": "Bahrain"},
    {"code": "BI", "description": "Burundi"},
    {"code": "BJ", "description": "Benin"},
    {"code": "BM", "description": "Bermuda"},
    {"code": "BN", "description": "Brunei Darussalam"},
    {"code": "BO", "description": "Bolivia"},
    {"code": "BR", "description": "Brazil"},
    {"code": "BS", "description": "Bahamas"},
    {"code": "BT", "description": "Bhutan"},
    {"code": "BV", "description": "Bouvet Island"},
    {"code": "BW", "description": "Botswana"},
    {"code": "BY", "description": "Belarus"},
    {"code": "BZ", "description": "Belize"},
    {"code": "CA", "description": "Canada"},
    {"code": "CC", "description": "Cocos (Keeling) Islands"},
    {"code": "CD", "description": "Congo, The Democratic Republic Of The"},
    {"code": "CF", "description": "Central African Republic"},
    {"code": "CG", "description": "Congo"},
    {"code": "CH", "description": "Switzerland"},
    {"code": "CI", "description": "Cote D’ivoire"},
    {"code": "CK", "description": "Cook Islands"},
    {"code": "CL", "description": "Chile"},
    {"code": "CM", "description": "Cameroon"},
    {"code": "CN", "description": "China"},
    {"code": "CO", "description": "Colombia"},
    {"code": "CR", "description": "Costa Rica"},
    {"code": "CV", "description": "Cape Verde"},
    {"code": "CW", "description": "Curaçao"},
    {"code": "CX", "description": "Christmas Island"},
    {"code": "CY", "description": "Cyprus"},
    {"code": "CZ", "description": "Czech Republic"},
    {"code": "DE", "description": "Germany"},
    {"code": "DJ", "description": "Djibouti"},
    {"code": "DK", "description": "Denmark"},
    {"code": "DM", "description": "Dominica"},
    {"code": "DO", "description": "Dominican Republic"},
    {"code": "DZ", "description": "Algeria"},
    {"code": "EC", "description": "Ecuador"},
    {"code": "EE", "description": "Estonia"},
    {"code": "EG", "description": "Egypt"},
    {"code": "EH", "description": "Western Sahara"},
    {"code": "ER", "description": "Eritrea"},
    {"code": "ES", "description": "Spain"},
    {"code": "ET", "description": "Estonia"},
    {"code": "FI", "description": "Finland"},
    {"code": "FJ", "description": "Fiji"},
    {"code": "FK", "description": "Falkland Islands (Malvinas)"},
    {"code": "FM", "description": "Micronesia, Federated States Of"},
    {"code": "FO", "description": "Faroe Islands"},
    {"code": "FR", "description": "France"},
    {"code": "FX", "description": "France, Metropolitan"},
    {"code": "GA", "description": "Gabon"},
    {"code": "GB", "description": "Great Britain"},
    {"code": "GD", "description": "Grenada"},
    {"code": "GE", "description": "Georgia"},
    {"code": "GF", "description": "French Guiana"},
    {"code": "GH", "description": "Ghana"},
    {"code": "GI", "description": "Gibraltar"},
    {"code": "GL", "description": "Greenland"},
    {"code": "GM", "description": "Gambia"},
    {"code": "GN", "description": "Guinea"},
    {"code": "GP", "description": "Guadeloupe"},
    {"code": "GQ", "description": "Equatorial Guinea"},
    {"code": "GR", "description": "Greece"},
    {"code": "GS", "description": "South Georgia And The South Sandwich Islands"},
    {"code": "GT", "description": "Guatemala"},
    {"code": "GU", "description": "Guam"},
    {"code": "GW", "description": "Guinea-Bissau"},
    {"code": "GY", "description": "Guyana"},
    {"code": "HK", "description": "Hong Kong"},
    {"code": "HM", "description": "Heard And Mc Donald Islands"},
    {"code": "HN", "description": "Honduras"},
    {"code": "HR", "description": "Croatia (Local Name: Hrvatska)"},
    {"code": "HT", "description": "Haiti"},
    {"code": "HU", "description": "Hungary"},
    {"code": "ID", "description": "Indonesia"},
    {"code": "IE", "description": "Ireland"},
    {"code": "IL", "description": "Israel"},
    {"code": "IN", "description": "India"},
    {"code": "IO", "description": "British Indian Ocean Territory"},
    {"code": "IQ", "description": "Iraq"},
    {"code": "IR", "description": "Iran (Islamic Republic Of)"},
    {"code": "IS", "description": "Iceland"},
    {"code": "IT", "description": "Italy"},
    {"code": "JM", "description": "Jamaica"},
    {"code": "JO", "description": "Jordan"},
    {"code": "JP", "description": "Japan"},
    {"code": "KE", "description": "Kenya"},
    {"code": "KG", "description": "Kyrgyzstan"},
    {"code": "KH", "description": "Cambodia"},
    {"code": "KI", "description": "Kiribati"},
    {"code": "KM", "description": "Comoros"},
    {"code": "KN", "description": "Saint Kitts And Nevis"},
    {"code": "KR", "description": "Korea, Republic Of"},
    {"code": "KW", "description": "Kuwait"},
    {"code": "KY", "description": "Cayman Islands"},
    {"code": "KZ", "description": "Kazakhstan"},
    {"code": "LA", "description": "Lao People’s Democratic Republic"},
    {"code": "LB", "description": "Lebanon"},
    {"code": "LC", "description": "Saint Lucia"},
    {"code": "LI", "description": "Liechtenstein"},
    {"code": "LK", "description": "Sri Lanka"},
    {"code": "LR", "description": "Liberia"},
    {"code": "LS", "description": "Lesotho"},
    {"code": "LT", "description": "Lithuania"},
    {"code": "LU", "description": "Luxembourg"},
    {"code": "LV", "description": "Latvia"},
    {"code": "LY", "description": "Libyan Arab Jamahiriya"},
    {"code": "MA", "description": "Morocco"},
    {"code": "MC", "description": "Monaco"},
    {"code": "MD", "description": "Moldova, Republic Of"},
    {"code": "MG", "description": "Madagascar"},
    {"code": "MH", "description": "Marshall Islands"},
    {"code": "MK", "description": "Macedonia, The Former Yugoslav Republic Of"},
    {"code": "ML", "description": "Mali"},
    {"code": "MM", "description": "Myanmar"},
    {"code": "MN", "description": "Mongolia"},
    {"code": "MO", "description": "Macau"},
    {"code": "MP", "description": "Northern Mariana Islands"},
    {"code": "MQ", "description": "Martinique"},
    {"code": "MR", "description": "Mauritania"},
    {"code": "MS", "description": "Montserrat"},
    {"code": "MT", "description": "Malta"},
    {"code": "MU", "description": "Mauritius"},
    {"code": "MV", "description": "Maldives"},
    {"code": "MW", "description": "Malawi"},
    {"code": "MX", "description": "Mexico"},
    {"code": "MY", "description": "Malaysia"},
    {"code": "MZ", "description": "Mozambique"},
    {"code": "NA", "description": "Namibia"},
    {"code": "NC", "description": "New Caledonia"},
    {"code": "NE", "description": "Niger"},
    {"code": "NF", "description": "Norfolk Island"},
    {"code": "NG", "description": "Nigeria"},
    {"code": "NI", "description": "Nicaragua"},
    {"code": "NL", "description": "Netherlands"},
    {"code": "NO", "description": "Norway"},
    {"code": "NP", "description": "Nepal"},
    {"code": "NR", "description": "Nauru"},
    {"code": "NU", "description": "Niue"},
    {"code": "NZ", "description": "New Zealand"},
    {"code": "OM", "description": "Oman"},
    {"code": "PA", "description": "Panama"},
    {"code": "PE", "description": "Peru"},
    {"code": "PF", "description": "French Polynesia"},
    {"code": "PG", "description": "Papua New Guinea"},
    {"code": "PH", "description": "Philippines"},
    {"code": "PK", "description": "Pakistan"},
    {"code": "PL", "description": "Poland"},
    {"code": "PM", "description": "St. Pierre And Miquelon"},
    {"code": "PN", "description": "Pitcairn"},
    {"code": "PR", "description": "Puerto Rico"},
    {"code": "PS", "description": "Palestinian Territory, Occupied"},
    {"code": "PT", "description": "Portugal"},
    {"code": "PW", "description": "Palau"},
    {"code": "PY", "description": "Paraguay"},
    {"code": "QA", "description": "Qatar"},
    {"code": "RE", "description": "Reunion"},
    {"code": "RO", "description": "Romania"},
    {"code": "RS", "description": "Serbia"},
    {"code": "RU", "description": "Russian Federation"},
    {"code": "RW", "description": "Rwanda"},
    {"code": "SA", "description": "Saudi Arabia"},
    {"code": "SB", "description": "Solomon Islands"},
    {"code": "SC", "description": "Seychelles"},
    {"code": "SD", "description": "Sudan"},
    {"code": "SE", "description": "Sweden"},
    {"code": "SG", "description": "Singapore"},
    {"code": "SH", "description": "St. Helena"},
    {"code": "SI", "description": "Slovenia"},
    {"code": "SJ", "description": "Svalbard And Jan Mayen Islands"},
    {"code": "SK", "description": "Slovakia (Slovak Republic)"},
    {"code": "SL", "description": "Sierra Leone"},
    {"code": "SM", "description": "San Marino"},
    {"code": "SN", "description": "Senegal"},
    {"code": "SO", "description": "Somalia"},
    {"code": "SR", "description": "Suriname"},
    {"code": "ST", "description": "Sao Tome And Principe"},
    {"code": "SV", "description": "El Salvador"},
    {"code": "SZ", "description": "Swaziland"},
    {"code": "TC", "description": "Turks And Caicos Islands"},
    {"code": "TD", "description": "Chad"},
    {"code": "TF", "description": "French Southern Territories"},
    {"code": "TG", "description": "Togo"},
    {"code": "TH", "description": "Thailand"},
    {"code": "TJ", "description": "Tajikistan"},
    {"code": "TK", "description": "Tokelau"},
    {"code": "TM", "description": "Turkmenistan"},
    {"code": "TN", "description": "Tunisia"},
    {"code": "TO", "description": "Tonga"},
    {"code": "TP", "description": "East Timor"},
    {"code": "TR", "description": "Turkey"},
    {"code": "TT", "description": "Trinidad And Tobago"},
    {"code": "TV", "description": "Tuvalu"},
    {"code": "TW", "description": "Taiwan, Province Of China"},
    {"code": "TZ", "description": "Tanzania, United Republic Of"},
    {"code": "UA", "description": "Ukraine"},
    {"code": "UG", "description": "Uganda"},
    {"code": "UK", "description": "United Kingdom"},
    {"code": "UM", "description": "United States Minor Outlying Islands"},
    {"code": "US", "description": "United States"},
    {"code": "UY", "description": "Uruguay"},
    {"code": "UZ", "description": "Uzbekistan"},
    {"code": "VA", "description": "Holy See (Vatican City State)"},
    {"code": "VC", "description": "Saint Vincent And The Grenadines"},
    {"code": "VE", "description": "Venezuela"},
    {"code": "VG", "description": "Virgin Islands (British)"},
    {"code": "VI", "description": "Virgin Islands (U.S.)"},
    {"code": "VN", "description": "Viet Nam"},
    {"code": "VU", "description": "Vanuatu"},
    {"code": "WF", "description": "Wallis And Futuna Islands"},
    {"code": "WS", "description": "Samoa"},
    {"code": "YE", "description": "Yemen"},
    {"code": "YT", "description": "Mayotte"},
    {"code": "YU", "description": "Yugoslavia"},
    {"code": "ZA", "description": "South Africa"},
    {"code": "ZM", "description": "Zambia"},
    {"code": "ZW", "description": "Zimbabwe"},
    {"code": "IM", "description": "Isle Of Man"},
    {"code": "AX", "description": "Åland Islands"},
    {"code": "BL", "description": "Saint Barthélemy"},
    {"code": "BQ", "description": "Bonaire, Sint Eustatius and Saba"},
    {"code": "GG", "description": "Guernsey"},
    {"code": "JE", "description": "Jersey"},
    {"code": "ME", "description": "Montenegro"},
    {"code": "MF", "description": "Saint Martin"},
    {"code": "SS", "description": "South Sudan"},
    {"code": "SX", "description": "Sint Maarten"},
    {"code": "TL", "description": "East Timor"},
    {"code": "AB", "description": "Abkhazia"},
    {"code": "XK", "description": "Kosovo"},
];
