export const CurrencyCodes = [
    {"code": "AED", "description": "United Arab Emirates Dirham"},
    {"code": "AFN", "description": "Afghani"},
    {"code": "ALL", "description": "Albania Lek"},
    {"code": "AMD", "description": "Armenia Dram"},
    {"code": "ANG", "description": "Netherlands Antillean guilder"},
    {"code": "AOA", "description": "Angola(Kwanza)"},
    {"code": "ARS", "description": "Argentina Pesos"},
    {"code": "AWG", "description": "Aruban florin"},
    {"code": "AZN", "description": "Azerbaijan Manat"},
    {"code": "BAM", "description": "Bosnia and Herzegovina Convertible Marka"},
    {"code": "BBD", "description": "Barbados Dollar"},
    {"code": "BDT", "description": "Bangladesh Taka"},
    {"code": "BGN", "description": "Bulgaria Lev"},
    {"code": "BHD", "description": "Bahraini dinar"},
    {"code": "BIF", "description": "Burundi Franc"},
    {"code": "BMD", "description": "Bermuda Dollar"},
    {"code": "BND", "description": "Brunei Dollar"},
    {"code": "BOB", "description": "Bolivia Boliviano"},
    {"code": "BRL", "description": "Brazil Real"},
    {"code": "BSD", "description": "Bahamian dollar"},
    {"code": "BTN", "description": "Bhutan Ngultrum"},
    {"code": "BWP", "description": "Botswana Pula"},
    {"code": "BYN", "description": "Belarusian Ruble"},
    {"code": "BZD", "description": "Belize Dollar"},
    {"code": "CAD", "description": "Canada Dollar"},
    {"code": "CDF", "description": "Congolese franc"},
    {"code": "CHF", "description": "Swiss franc"},
    {"code": "CLP", "description": "Chile Peso"},
    {"code": "CNY", "description": "China Yuan Renminbi"},
    {"code": "COP", "description": "Colombia Pesos"},
    {"code": "CRC", "description": "Costa Rica Colon"},
    {"code": "RSD", "description": "Serbia Dinar"},
    {"code": "CVE", "description": "Cape Verde Escudo"},
    {"code": "CZK", "description": "Czech koruna"},
    {"code": "DJF", "description": "Djiboutian Franc"},
    {"code": "DKK", "description": "Danish krone"},
    {"code": "DOP", "description": "Dominican peso"},
    {"code": "DZD", "description": "Algeria Dinar"},
    {"code": "EGP", "description": "Egypt Pounds"},
    {"code": "ERN", "description": "Eritrea Nakfa"},
    {"code": "ETB", "description": "Ethiopian Birr"},
    {"code": "EUR", "description": "Euro"},
    {"code": "FJD", "description": "Fiji Dollar"},
    {"code": "FKP", "description": "Falkland Island Pound"},
    {"code": "GBP", "description": "Pound sterling"},
    {"code": "GEL", "description": "Georgian lari"},
    {"code": "GHS", "description": "Ghanaian Cedis"},
    {"code": "GIP", "description": "Gibraltar Pound"},
    {"code": "GMD", "description": "Gambia Dalasi"},
    {"code": "GNF", "description": "Guinea Franc"},
    {"code": "GTQ", "description": "Guatemala Quetzal"},
    {"code": "GYD", "description": "Guyana Dollar"},
    {"code": "HKD", "description": "Hong kong Dollar"},
    {"code": "HNL", "description": "Honduran lempira"},
    {"code": "HRK", "description": "Croatia Kuna"},
    {"code": "HTG", "description": "Haiti Gourde"},
    {"code": "HUF", "description": "Hungary Forint"},
    {"code": "IDR", "description": "Indonesia Rupiah"},
    {"code": "ILS", "description": "Israel New Shekel"},
    {"code": "INR", "description": "India Rupee"},
    {"code": "IQD", "description": "Iraq Dinar"},
    {"code": "ISK", "description": "Icelandic króna"},
    {"code": "JMD", "description": "Jamaica Dollar"},
    {"code": "JOD", "description": "Jordan Dinar"},
    {"code": "JPY", "description": "Japan Yen"},
    {"code": "KES", "description": "Kenya Shilling"},
    {"code": "KGS", "description": "Kyrgyzstan Som"},
    {"code": "KHR", "description": "Cambodia Riel"},
    {"code": "KMF", "description": "Comoros Franc"},
    {"code": "KRW", "description": "South Korea Won"},
    {"code": "KWD", "description": "Kuwait Dinar"},
    {"code": "KYD", "description": "Cayman Islands Dollar"},
    {"code": "LAK", "description": "Laos Kip"},
    {"code": "LBP", "description": "Lebanon Pound"},
    {"code": "LRD", "description": "Liberia Dollar"},
    {"code": "LSL", "description": "Lesotho Loti"},
    {"code": "LYD", "description": "Libya Dinar"},
    {"code": "MAD", "description": "Morocco Dirham"},
    {"code": "MDL", "description": "Moldova Leu"},
    {"code": "MGA", "description": "Malagasy ariary"},
    {"code": "MKD", "description": "Macedonia Denar"},
    {"code": "MMK", "description": "Myanmar Kyat"},
    {"code": "MNT", "description": "Mongolian Tugrik"},
    {"code": "MOP", "description": "Macau Pataca"},
    {"code": "MUR", "description": "Mauritius Rupee"},
    {"code": "MVR", "description": "Maldives Rufiyaa"},
    {"code": "MWK", "description": "Malawi Kwacha"},
    {"code": "MXN", "description": "Mexico Peso"},
    {"code": "MYR", "description": "Malaysia Ringgit"},
    {"code": "NAD", "description": "Namibian dollar"},
    {"code": "NGN", "description": "Nigeria Naira"},
    {"code": "NIO", "description": "Nicaragua Cordola"},
    {"code": "NOK", "description": "Norwegian krone"},
    {"code": "NPR", "description": "Nepal Rupee"},
    {"code": "NZD", "description": "New Zealand Dollar"},
    {"code": "OMR", "description": "Oman Rial"},
    {"code": "PAB", "description": "Panama Balboa"},
    {"code": "PEN", "description": "Peruvian sol"},
    {"code": "PGK", "description": "Papua New Guinea Kina"},
    {"code": "PHP", "description": "Philippines Peso"},
    {"code": "PKR", "description": "Pakistan Rupee"},
    {"code": "PLN", "description": "Poland Zloty"},
    {"code": "PYG", "description": "Paraguay Guarani"},
    {"code": "QAR", "description": "Qatar Riyal"},
    {"code": "RON", "description": "Romanian Leu"},
    {"code": "RUB", "description": "Russia Ruble"},
    {"code": "RWF", "description": "Rwanda Franc"},
    {"code": "SAR", "description": "Saudi Arabia Riyal"},
    {"code": "SBD", "description": "Solomon Islands Dollar"},
    {"code": "SCR", "description": "Seychelles Rupee"},
    {"code": "SDG", "description": "Sudanese Pound"},
    {"code": "SEK", "description": "Swedish Krona"},
    {"code": "SGD", "description": "Singapore Dollar"},
    {"code": "SHP", "description": "Saint Helena Pound"},
    {"code": "SLL", "description": "Sierra Leone"},
    {"code": "SOS", "description": "Somalia Shilling"},
    {"code": "SRD", "description": "Suriname Dollar"},
    {"code": "SVC", "description": "El Salvador Colón"},
    {"code": "SZL", "description": "Swazi lilangeni"},
    {"code": "THB", "description": "Thailand Baht"},
    {"code": "TJS", "description": "Tajikistan Somoni"},
    {"code": "TMT", "description": "Turkmenistan manat"},
    {"code": "TND", "description": "Tunisia Dinar"},
    {"code": "TOP", "description": "Tonga Pa’anga"},
    {"code": "TRY", "description": "Turkish lira"},
    {"code": "TTD", "description": "Trinidad and Tabago Dollar"},
    {"code": "TWD", "description": "Taiwan New Dollar"},
    {"code": "TZS", "description": "Tanzania Shilling"},
    {"code": "UAH", "description": "Ukrainian hryvnia"},
    {"code": "UGX", "description": "Uganda Shilling"},
    {"code": "USD", "description": "US Dollars"},
    {"code": "UYU", "description": "Uruguay Peso"},
    {"code": "UZS", "description": "Uzbekistan Som"},
    {"code": "VES", "description": "Venezuelan bolívar soberano"},
    {"code": "VND", "description": "Vietnam Dong"},
    {"code": "VUV", "description": "Vanuatu Vatu"},
    {"code": "WST", "description": "Samoa Tala"},
    {"code": "XAG", "description": "Silver Ounce"},
    {"code": "XAF", "description": "CFA Franc BEAC"},
    {"code": "XAU", "description": "Gold Ounce"},
    {"code": "XCD", "description": "East Carribbean Dollar"},
    {"code": "XDR", "description": "INTERNATIONAL MONETARY FUND (IMF) SDR (Special Drawing Right)"},
    {"code": "XOF", "description": "CFA franc BCEAO"},
    {"code": "XPD", "description": "Palladium Ounce"},
    {"code": "XPF", "description": "CFP franc (franc Pacifique)"},
    {"code": "XPT", "description": "Platinum Ounce"},
    {"code": "YER", "description": "Yemen Rial"},
    {"code": "ZAR", "description": "South Africa Rand"},
    {"code": "ZMW", "description": "Zambia Kwacha"},
]