export const LanguageCodes = [
    {"description": "Albanian", "code": "al"},
    {"description": "Albanian", "code": "sq"},
    {"description": "Arabic", "code": "ar"},
    {"description": "Armenian", "code": "hy"},
    {"description": "Brazilian Portuguese", "code": "bp"},
    {"description": "Bulgarian", "code": "bg"},
    {"description": "Canadian French", "code": "cf"},
    {"description": "Catalan, Valencian", "code": "ca"},
    {"description": "Chinese (Simplified)", "code": "cn"},
    {"description": "Chinese (Simplified)", "code": "zh"},
    {"description": "Chinese (Traditional)", "code": "b5"},
    {"description": "Croatian", "code": "hr"},
    {"description": "Czech", "code": "cs"},
    {"description": "Danish", "code": "dk"},
    {"description": "Danish", "code": "da"},
    {"description": "Dutch", "code": "nl"},
    {"description": "English", "code": "en"},
    {"description": "Estonian", "code": "et"},
    {"description": "Finnish", "code": "fi"},
    {"description": "Flemish", "code": "fl"},
    {"description": "French", "code": "fr"},
    {"description": "Georgian", "code": "ka"},
    {"description": "German", "code": "de"},
    {"description": "Greek (modern)", "code": "el"},
    {"description": "Hebrew", "code": "he"},
    {"description": "Hindi", "code": "hi"},
    {"description": "Hungarian", "code": "hu"},
    {"description": "Indonesian", "code": "id"},
    {"description": "Italian", "code": "it"},
    {"description": "Japanese", "code": "ja"},
    {"description": "Korean", "code": "ko"},
    {"description": "Latvian", "code": "lv"},
    {"description": "Lithuanian", "code": "lt"},
    {"description": "Malay", "code": "ms"},
    {"description": "Mongolian", "code": "mn"},
    {"description": "Norwegian", "code": "no"},
    {"description": "Polish", "code": "pl"},
    {"description": "Portuguese", "code": "pt"},
    {"description": "Romanian, Moldavian, Moldovan", "code": "ro"},
    {"description": "Russian", "code": "ru"},
    {"description": "Serbian", "code": "sr"},
    {"description": "Slovak", "code": "sk"},
    {"description": "Slovenian", "code": "sl"},
    {"description": "Spanish, Castilian", "code": "es"},
    {"description": "Swedish", "code": "sv"},
    {"description": "Thai", "code": "th"},
    {"description": "Turkish", "code": "tr"},
    {"description": "Ukrainian", "code": "ua"},
    {"description": "Ukrainian", "code": "uk"},
    {"description": "Vietnamese", "code": "vi"},
];
